name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      #Build without testing so we know whether it builds
    - name: Build
      run: ./gradlew build -x test

  test:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      #Test subsystems first, as they are the lowest-level tests
    - name: Test Subsystems
      run: ./gradlew subsystemTest
    - name: Test results
      if: ${{ failure() }}
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: build/reports/subsystemTest/
      #Command tests depend on subsystems, so they are next
    - name: Test commands
      run: ./gradlew commandTest
    - name: Test results
      if: ${{ failure() }}
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: build/reports/commandTest/
      #Auto commands depend on commands, so they are next
    - name: Test auto commands
      run: ./gradlew autoTest
    - name: Test results
      if: ${{ failure() }}
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: build/reports/autoTest/
      #Finally simulation tests may include many of the above
    - name: Simulation tests
      run: ./gradlew simTest
    - name: Test results
      if: ${{ failure() }}
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: build/reports/simTest/
